#!/bin/bash

# File to keep the current brightness level
BRIGHTNESS_FILE="$HOME/.current_brightness"

# Check if the brightness file exists, if not create it with a default value
if [ ! -f "$BRIGHTNESS_FILE" ]; then
  echo 50 >"$BRIGHTNESS_FILE"
fi

# Read the current brightness level
CURRENT_BRIGHTNESS=$(cat "$BRIGHTNESS_FILE")

# Get the direction of the adjustment
ADJUSTMENT=$1

# Adjustment value
ADJUSTMENT_VALUE=3

# Determine new brightness level
if [ "$ADJUSTMENT" == "up" ]; then
  NEW_BRIGHTNESS=$((CURRENT_BRIGHTNESS + ADJUSTMENT_VALUE))
elif [ "$ADJUSTMENT" == "down" ]; then
  NEW_BRIGHTNESS=$((CURRENT_BRIGHTNESS - ADJUSTMENT_VALUE))
else
  echo "Usage: $0 {up|down}"
  exit 1
fi

# Make sure the brightness level is between 0 and 100
if [ "$NEW_BRIGHTNESS" -lt 0 ]; then
  NEW_BRIGHTNESS=0
elif [ "$NEW_BRIGHTNESS" -gt 100 ]; then
  NEW_BRIGHTNESS=100
fi

# Set the new brightness level
ddccontrol -r 0x10 -w "$NEW_BRIGHTNESS" dev:/dev/i2c-4

# Save the new brightness level
echo "$NEW_BRIGHTNESS" >"$BRIGHTNESS_FILE"
